name: tiled-exporter
description: Exports tmx files to png and/or json
author: Oliver Lorenz
inputs:
  tmx_file:
    description: "tmx file to convert"
    required: true
  export_json:
    description: "export json version of tmx file"
    required: false
  export_png:
    description: "export png version of tmx file"
    required: false
  
runs:
  using: docker
  image: 'Dockerfile'
branding:
  icon: 'message-square'
  color: 'blue'